#!/bin/sh
# =============================================================================
# Iris Classification Spark Example - Quick Setup Script
# =============================================================================
# This script creates the required configuration for the iris classification
# end-to-end example. It generates .setup/enabled-services.yaml with:
#   - Compute (darwin-compute, darwin-cluster-manager)
#   - MLflow (darwin-mlflow, darwin-mlflow-app)
#   - Serve (ml-serve-app, artifact-builder)
#   - Ray image: ray:2.37.0
#   - Darwin SDK Runtime (Ray + Spark support)
#   - Darwin CLI
# =============================================================================

set -e

# Navigate to project root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Iris Classification Spark Example - Quick Setup            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Project root: $PROJECT_ROOT"
echo ""

# Check if yq is available
if ! command -v yq >/dev/null 2>&1; then
  echo "❌ yq is required but not installed."
  echo "   Please run setup.sh first to install dependencies, or install yq manually."
  exit 1
fi

# Create .setup directory if it doesn't exist
mkdir -p .setup

OUTPUT_FILE=".setup/enabled-services.yaml"

# Check if config already exists
if [ -f "$OUTPUT_FILE" ]; then
  printf "⚠️  Configuration already exists at $OUTPUT_FILE. Overwrite? (y/n) "
  read REPLY
  case "$REPLY" in
    [Yy]|[Yy][Ee][Ss]) ;;
    *)
      echo "Keeping existing configuration."
      exit 0
      ;;
  esac
fi

echo "📋 Generating configuration for iris-classification example..."
echo ""

# Generate the enabled-services.yaml
cat > "$OUTPUT_FILE" << 'EOF'
# Darwin Distribution - Enabled Services Configuration
# Generated by examples/iris-classification/init-example.sh
#
# This configuration enables the services required for the
# iris classification Spark end-to-end example:
#   - Compute cluster management
#   - MLflow for experiment tracking and model registry
#   - ML-Serve for model deployment
#   - Darwin SDK Runtime for Spark support

applications:
  darwin-ofs-v2: false
  darwin-ofs-v2-admin: false
  darwin-ofs-v2-consumer: false
  darwin-mlflow: true  # (direct) - MLflow tracking server
  darwin-mlflow-app: true  # (direct) - MLflow application
  chronos: false
  chronos-consumer: false
  darwin-compute: true  # (direct) - Compute cluster management
  darwin-cluster-manager: true  # (dependency) - Required by darwin-compute
  darwin-workspace: false
  ml-serve-app: true  # (direct) - Model serving
  artifact-builder: true  # (dependency) - Required by ml-serve-app
  darwin-workflow: false
  darwin-catalog: false

ray-images:
  "ray:2.37.0": true  # (selected) - Base Ray runtime
  "ray:2.53.0": false

serve-images:
  "serve-md-runtime:latest": true  # (auto-enabled with ml-serve-app)

datastores:
  mysql: true  # Required by compute, mlflow, serve
  cassandra: false
  kafka: false
  zookeeper: false
  airflow: false
  rabbitmq: false
  localstack: true  # Required for S3-compatible storage
  opensearch: true  # Required by compute
  elasticsearch: false
  busybox: true  # Init container

darwin-sdk-runtime:
  enabled: true  # Ray + Spark + Darwin SDK

cli-tools:
  darwin-cli: true  # CLI for cluster and serve management
EOF

echo "✅ Configuration saved to: $OUTPUT_FILE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                     ENABLED SERVICES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 Applications:"
echo "   ✓ darwin-compute (direct)"
echo "   ✓ darwin-cluster-manager (dependency)"
echo "   ✓ darwin-mlflow (direct)"
echo "   ✓ darwin-mlflow-app (direct)"
echo "   ✓ ml-serve-app (direct)"
echo "   ✓ artifact-builder (dependency)"
echo ""
echo "🔷 Ray Images:"
echo "   ✓ ray:2.37.0"
echo ""
echo "🔷 Darwin SDK Runtime:"
echo "   ✓ ray:2.37.0-darwin-sdk (Ray + Spark + Darwin SDK)"
echo ""
echo "🚀 Serve Images:"
echo "   ✓ serve-md-runtime:latest"
echo ""
echo "🗄️  Datastores:"
echo "   ✓ mysql"
echo "   ✓ localstack"
echo "   ✓ opensearch"
echo "   ✓ busybox"
echo ""
echo "🛠️  CLI Tools:"
echo "   ✓ darwin-cli"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                        NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Build images and setup cluster:"
echo "     ./setup.sh -y"
echo ""
echo "  2. Deploy the platform:"
echo "     ./start.sh"
echo ""
echo "  3. Follow the example guide:"
echo "     See examples/iris-classification/README.md"
echo ""
