#!/bin/sh
# =============================================================================
# LightGBM Wine Classification Spark Example - Quick Setup Script
# =============================================================================
# This script creates the required configuration for the wine classification
# end-to-end example. It generates .setup/enabled-services.yaml with:
#   - Training preset: Compute + MLflow
#   - Inference preset: Serve + MLflow
#   - Ray image: ray:2.37.0
#   - Darwin SDK Runtime (Ray + Spark support)
#   - Darwin CLI
# =============================================================================

set -e

# Navigate to project root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   LightGBM Wine Classification Spark Example - Quick Setup     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Project root: $PROJECT_ROOT"
echo ""

# Check if yq is available
if ! command -v yq >/dev/null 2>&1; then
  echo "❌ yq is required but not installed."
  echo "   Please run setup.sh first to install dependencies, or install yq manually."
  exit 1
fi

# Create .setup directory if it doesn't exist
mkdir -p .setup

OUTPUT_FILE=".setup/enabled-services.yaml"

# Check if config already exists
if [ -f "$OUTPUT_FILE" ]; then
  printf "⚠️  Configuration already exists at $OUTPUT_FILE. Overwrite? (y/n) "
  read REPLY
  case "$REPLY" in
    [Yy]|[Yy][Ee][Ss]) ;;
    *)
      echo "Keeping existing configuration."
      exit 0
      ;;
  esac
fi

echo "📋 Generating configuration for lightgbm-wine-classification example..."
echo "   This enables both Training and Inference presets:"
echo "   • Training (Compute + MLflow)"
echo "   • Inference (Serve + MLflow)"
echo ""

# Generate the enabled-services.yaml
cat > "$OUTPUT_FILE" << 'EOF'
# Darwin Distribution - Enabled Services Configuration
# Generated by examples/lightgbm-wine-classification/init-example.sh on $(date)
#
# Legend:
#   (direct)     - Directly selected by user
#   (dependency) - Auto-enabled due to dependencies

applications:
  darwin-ofs-v2: false
  darwin-ofs-v2-admin: false
  darwin-ofs-v2-consumer: false
  darwin-mlflow: true  # (direct)
  darwin-mlflow-app: true  # (direct)
  chronos: false
  chronos-consumer: false
  darwin-compute: true  # (direct)
  darwin-cluster-manager: true  # (dependency)
  darwin-workspace: false
  ml-serve-app: true  # (direct)
  artifact-builder: true  # (dependency)
  darwin-workflow: false
  darwin-catalog: false

ray-images:
  "ray:2.37.0": true  # (selected)
  "ray:2.53.0": false

serve-images:
  "serve-md-runtime:latest": true  # (auto-enabled with ml-serve-app)

datastores:
  mysql: true
  cassandra: false
  kafka: false
  zookeeper: false
  airflow: false
  rabbitmq: false
  localstack: true
  opensearch: true
  elasticsearch: false
  busybox: true

darwin-sdk-runtime:
  enabled: true

cli-tools:
  darwin-cli: true
EOF

echo "✅ Configuration saved to: $OUTPUT_FILE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                        CONFIGURATION SAVED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Enabled services:"
echo ""
echo "📦 Applications:"
echo "   ✓ darwin-compute (direct)"
echo "   ✓ darwin-cluster-manager (dependency)"
echo "   ✓ darwin-mlflow (direct)"
echo "   ✓ darwin-mlflow-app (direct)"
echo "   ✓ ml-serve-app (direct)"
echo "   ✓ artifact-builder (dependency)"
echo ""
echo "🔷 Ray Images (selected):"
echo "   ✓ ray:2.37.0"
echo ""
echo "🚀 Serve Images (auto-enabled with ml-serve-app):"
echo "   ✓ serve-md-runtime:latest"
echo ""
echo "🗄️  Datastores:"
echo "   ✓ mysql"
echo "   ✓ localstack"
echo "   ✓ opensearch"
echo "   ✓ busybox"
echo ""
echo "🛠️  CLI Tools:"
echo "   ✓ darwin-cli"
echo ""
echo "🔷 Darwin SDK Runtime:"
echo "   ✓ ray:2.37.0-darwin-sdk (Ray + Spark + Darwin SDK)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                        DEPENDENCY SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Features selected by user:"
echo "   • Compute"
echo "   • MLflow"
echo "   • Serve"
echo ""
echo "Services auto-enabled as dependencies:"
echo "   → darwin-cluster-manager"
echo "   → artifact-builder"
echo ""
echo "Next steps:"
echo "  1. Run ./setup.sh to build images and set up the cluster"
echo "  2. Run ./start.sh to deploy the platform"
echo ""
