package com.dream11.core.error;

import com.dream11.rest.exception.RestError;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.ToString;

// TODO: Error codes are inconsistent - some use hyphens (ENTITY-REGISTRATION-ERROR), some use underscores.
// TODO: Error messages are generic ("invalid request") - add more context for debugging.
// TODO: Consider grouping errors by domain (Entity, FeatureGroup, Tenant, Consumer) for better organization.
@Getter
@ToString
@RequiredArgsConstructor
public enum ServiceError implements RestError {
  SERVICE_UNKNOWN_EXCEPTION("DarwinOfsV2-UNKNOWN-EXCEPTION", "Something went wrong", 500),
  ENTITY_REGISTRATION_EXCEPTION("ENTITY-REGISTRATION-ERROR", "error while registering entity", 500),
  ENTITY_REGISTRATION_INVALID_REQUEST_EXCEPTION(
      "ENTITY-REGISTRATION-REQUEST-EXCEPTION", "invalid request", 400),
  ENTITY_ALREADY_EXISTS_EXCEPTION("ENTITY-ALREADY-EXISTS-EXCEPTION", "entity already exists", 400),
  GET_ENTITY_EXCEPTION("GET-ENTITY-EXCEPTION", "error while getting entity", 500),
  ENTITY_NOT_FOUND_EXCEPTION("ENTITY-NOT-FOUND-EXCEPTION", "entity not found", 404),
  ENTITY_SCHEMA_VALIDATION_EXCEPTION(
      "ENTITY-SCHEMA-VALIDATION-EXCEPTION", "invalid entity schema", 400),
  ENTITY_VERSION_NOT_FOUND_EXCEPTION(
      "ENTITY-VERSION-NOT-FOUND-EXCEPTION", "entity version not found", 404),
  FEATURE_GROUP_REGISTRATION_EXCEPTION(
      "FEATURE-GROUP-REGISTRATION-ERROR", "error while registering feature group", 500),
  FEATURE_GROUP_REGISTRATION_INVALID_REQUEST_EXCEPTION(
      "FEATURE-GROUP-REGISTRATION-REQUEST-EXCEPTION", "invalid request", 400),
  FEATURE_GROUP_REGISTRATION_INVALID_COLUMN_NAMES_EXCEPTION(
      "FEATURE-GROUP-INVALID-COLUMN-NAMES-EXCEPTION",
      "either columns with feature names already in the entity table or duplicates in feature column names",
      400),
  FEATURE_GROUP_ALREADY_EXISTS_EXCEPTION(
      "FEATURE-GROUP-ALREADY-EXISTS-EXCEPTION", "feature group already exists", 400),
  GET_FEATURE_GROUP_EXCEPTION(
      "GET-FEATURE-GROUP-EXCEPTION", "error while getting feature group", 500),
  FEATURE_GROUP_NOT_FOUND_EXCEPTION(
      "FEATURE-GROUP-NOT-FOUND-EXCEPTION", "feature group not found", 404),
  FEATURE_GROUP_VERSION_NOT_FOUND_EXCEPTION(
      "FEATURE-GROUP-VERSION-NOT-FOUND-EXCEPTION", "feature group version not found", 404),
  FEATURE_GROUP_SCHEMA_VALIDATION_EXCEPTION(
      "FEATURE-GROUP-SCHEMA-VALIDATION-EXCEPTION", "invalid feature group schema", 400),
  WRITE_FEATURE_GROUP_INVALID_REQUEST_EXCEPTION(
      "WRITE-FEATURE-GROUP-REQUEST-EXCEPTION", "invalid request", 400),
  READ_FEATURE_GROUP_INVALID_REQUEST_EXCEPTION(
      "READ-FEATURE-GROUP-REQUEST-EXCEPTION", "invalid request", 400),
  READ_FEATURE_GROUP_PARTITION_INVALID_REQUEST_EXCEPTION(
      "READ-FEATURE-GROUP-PARTITION-REQUEST-EXCEPTION", "invalid request", 400),
  MULTI_READ_FEATURE_GROUP_INVALID_REQUEST_EXCEPTION(
      "MULTI-READ-FEATURE-GROUP-REQUEST-EXCEPTION", "invalid request", 400),
  MULTI_READ_FEATURE_GROUP_INVALID_REQUEST_BAD_BATCH_SIZE_EXCEPTION(
      "MULTI-READ-FEATURE-GROUP-INVALID-BATCH-SIZE-EXCEPTION", "number of rows per cannot be greater than 10", 400),
  OWNERS_NOT_FOUND_EXCEPTION("OWNERS-NOT-FOUND-EXCEPTION", "owners not found", 404),
  SEARCH_FEATURE_GROUP_INVALID_REQUEST_EXCEPTION(
      "SEARCH-FEATURE-GROUP-REQUEST-EXCEPTION", "invalid request", 400),
  SEARCH_ENTITY_INVALID_REQUEST_EXCEPTION(
      "SEARCH-ENTITY-REQUEST-EXCEPTION", "invalid request", 400),
  ENTITY_UPDATE_INVALID_REQUEST_EXCEPTION(
      "UPDATE-ENTITY-REQUEST-EXCEPTION", "entity has feature groups associated with it", 400),
  ENTITY_STATE_INVALID_EXCEPTION("ENTITY-STATE-EXCEPTION", "entity is archived", 400),
  FEATURE_GROUP_STATE_INVALID_EXCEPTION(
      "FEATURE-GROUP-STATE-EXCEPTION", "feature group is archived", 400),
  WEB_CLIENT_EXCEPTION("WEB-CLIENT-EXCEPTION", "", 500),
  OFS_V2_ADMIN_SERVICE_UNKNOWN_EXCEPTION("OFS-V2-ADMIN-SERVICE-EXCEPTION", "", 500),
  OFS_V2_ADMIN_SERVICE_EXCEPTION("OFS-V2-ADMIN-SERVICE-EXCEPTION", "", 400),
  VERSIONING_DISABLED_EXCEPTION(
      "VERSIONING-DISABLED-EXCEPTION", "versioning disabled for feature group", 400),
  CONSUMER_ASSIGNMENT_NOT_FOUND(
      "CONSUMER-CONFIG-NOT-FOUND-EXCEPTION", "consumer assignment not found", 400),
  OFS_V2_SERVICE_UNKNOWN_EXCEPTION("OFS-V2-SERVICE-EXCEPTION", "", 500),
  OFS_V2_TENANT_NOT_FOUND_EXCEPTION("OFS-V2-TENANT-NOT-FOUND-EXCEPTION", "tenant not found", 400),
  OFS_V2_KAFKA_ADMIN_EXCEPTION("OFS-V2-KAFKA-ADMIN-EXCEPTION", "", 400),
  CONSUMER_CONFIG_NOT_FOUND_EXCEPTION("OFS-V2-CONSUMER-CONFIG-NOT-FOUND-EXCEPTION", "consumer config not found", 400),
  OFS_V2_TENANT_ONBOARDING_EXCEPTION("OFS-V2-TENANT-ONBOARDING-EXCEPTION", "error onboarding tenant", 500),
  OFS_V2_CONSUMER_REGISTRATION_EXCEPTION("OFS-V2-CONSUMER-REGISTRATION-EXCEPTION", "error registering consumer", 500),
  OFS_V2_METASTORE_UNAVAILABLE_EXCEPTION("OFS-V2-METASTORE-UNAVAILABLE-EXCEPTION", "metastore unavailable", 500),
  OFS_V2_TTL_UPDATE_EXCEPTION("OFS-V2-TTL-UPDATE-EXCEPTION", "error updating ttl", 500),
  METASTORE_RUN_EXCEPTION("METASTORE-RUN-EXCEPTION", "error putting metastore run", 500),
  OFS_V2_KAFKA_CONFIG_NOT_FOUND_EXCEPTION("OFS-V2-KAFKA-CONFIG-NOT-FOUND-EXCEPTION", "kafka config backup not found", 400);

  final String errorCode;
  final String errorMessage;
  final int httpStatusCode;
}
